name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v1
      - 
        name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - 
        name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - 
        name: Install CRC32
        run: |
          $env:Path = "C:\Strawberry\perl\bin;" + $env:Path
          [Environment]::SetEnvironmentVariable("Path", "C:\Strawberry\perl\bin;" + $env:Path, "User")
          cpan String::CRC32
      - 
        name: Add registry key(s)
        run: |
          $path = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}"

          if (!(Test-Path $path)) {
            New-Item $path -Force;
          }

          New-ItemProperty -Path $path -Name "DefaultProjectExtension" -Value "vcproj" -PropertyType String -Force
      - 
        name: Generate all projects
        working-directory: src
        run: |
          .\createallprojects.bat
      - 
        name: Generate core projects
        working-directory: src
        run: |
          .\createcoreprojects.bat
      - 
        name: Build all core projects
        working-directory: src
        run: |
          devenv core.sln /Build "Release|x86"
      - name: Cache shaders
        id: cache-shaders
        uses: actions/cache@v1
        with:
          path: src/materialsystem/stdshaders/shaders
          key: ${{ runner.os }}-shaders
      -
        name: Build all shaders
        working-directory: src/materialsystem/stdshaders
        run: |
          $env:Path = "C:\Strawberry\perl\bin;" + $env:Path
          .\_buildallshaders.bat
