name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v1
      - 
        name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - 
        name: Install CRC32
        run: |
          $env:Path = "C:\Strawberry\perl\bin;" + $env:Path
          cpan String::CRC32
      - 
        name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - 
        name: Add registry key(s)
        run: |
          $path = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}"

          if (!(Test-Path $path)) {
            New-Item $path -Force;
          }

          New-ItemProperty -Path $path -Name "DefaultProjectExtension" -Value "vcproj" -PropertyType String -Force
      - 
        name: Generate all projects
        working-directory: src
        run: |
          .\createallprojects.bat
      - 
        name: Build all core projects
        working-directory: src
        run: |
          msbuild everything.sln /t:Build /p:Configuration=Release
      - 
        name: Build all shaders
        working-directory: src/materialsystem/stdshaders
        run: |
          .\_buildallshaders.bat
