name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v1
      - 
        name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - 
        name: Install Perl
        uses: crazy-max/ghaction-chocolatey@v1.0.2
        with:
          # Arguments to pass to Chocolatey
          args: install strawberryperl
      - name: Install CRC32
        run: |
          refreshenv
          cpan String::CRC32
      - name: Generate all projects
        run: |
          src/createallprojects.bat
      - name: Build all core projects
        run: |
          msbuild src/core.sln /t:Build /p:Configuration=Release
      - 
        name: Build all shaders
        run: |
          src/materialsystem/stdshaders/_buildallshaders.bat
